// Copyright 2026 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package main

import (
	"fmt"
	"go/ast"
	"io"
	"strings"

	"internal/buildcfg"
)

const cgoDirectVersion = "v1"

type cgoDirectType string

const (
	cgoDirectInt8    cgoDirectType = "i8"
	cgoDirectInt16   cgoDirectType = "i16"
	cgoDirectInt32   cgoDirectType = "i32"
	cgoDirectInt64   cgoDirectType = "i64"
	cgoDirectUint8   cgoDirectType = "u8"
	cgoDirectUint16  cgoDirectType = "u16"
	cgoDirectUint32  cgoDirectType = "u32"
	cgoDirectUint64  cgoDirectType = "u64"
	cgoDirectPointer cgoDirectType = "ptr"
	cgoDirectVoid    cgoDirectType = "void"
)

type cgoDirectCall struct {
	wrapper string
	direct  string
	symbol  string
	entry   string
	params  []cgoDirectType
	result  cgoDirectType
	errno   bool
}

func (p *Package) directCall(n *Name) (cgoDirectCall, bool) {
	if !cgoDirectSupported() || *gccgo || n.Kind != "func" ||
		n.FuncType == nil || n.AddError || !p.noCallbacks[n.C] ||
		!validCgoDirectSymbol(n.C) {
		return cgoDirectCall{}, false
	}

	const maxRegisterParams = 6
	if len(n.FuncType.Params) > maxRegisterParams {
		return cgoDirectCall{}, false
	}
	params := make([]cgoDirectType, len(n.FuncType.Params))
	for i, param := range n.FuncType.Params {
		var ok bool
		params[i], ok = cgoDirectTypeOf(param)
		if !ok || params[i] == cgoDirectVoid {
			return cgoDirectCall{}, false
		}
	}

	result := cgoDirectVoid
	if n.FuncType.Result != nil {
		var ok bool
		result, ok = cgoDirectTypeOf(n.FuncType.Result)
		if !ok || result == cgoDirectVoid {
			return cgoDirectCall{}, false
		}
	}

	const wrapperPrefix = "_Cfunc_"
	if !strings.HasPrefix(n.Mangle, wrapperPrefix) {
		return cgoDirectCall{}, false
	}
	direct := "_Cdirect_" + strings.TrimPrefix(n.Mangle, wrapperPrefix)
	return cgoDirectCall{
		wrapper: n.Mangle,
		direct:  direct,
		symbol:  n.C,
		entry:   fmt.Sprintf("_cgo%s%s_direct", cPrefix, n.Mangle),
		params:  params,
		result:  result,
		errno:   n.AddError,
	}, true
}

func cgoDirectSupported() bool {
	if !buildcfg.Experiment.Coro {
		return false
	}
	return buildcfg.GOOS == "darwin" && buildcfg.GOARCH == "arm64" ||
		buildcfg.GOOS == "linux" && buildcfg.GOARCH == "amd64"
}

func validCgoDirectSymbol(name string) bool {
	if name == "" || !isCgoDirectIdentStart(name[0]) {
		return false
	}
	for i := 1; i < len(name); i++ {
		if !isCgoDirectIdentStart(name[i]) && (name[i] < '0' || name[i] > '9') {
			return false
		}
	}
	return true
}

func isCgoDirectIdentStart(ch byte) bool {
	return ch == '_' || ch >= 'a' && ch <= 'z' || ch >= 'A' && ch <= 'Z'
}

func (call cgoDirectCall) writeDirective(w io.Writer) {
	params := "-"
	if len(call.params) != 0 {
		names := make([]string, len(call.params))
		for i, param := range call.params {
			names[i] = string(param)
		}
		params = strings.Join(names, ",")
	}
	errno := "-"
	if call.errno {
		errno = "errno"
	}
	fmt.Fprintf(w, "//go:cgo_direct %s %s %s %s mayblock %s %s %s\n",
		cgoDirectVersion, call.wrapper, call.direct, call.symbol,
		params, call.result, errno)
}

func (p *Package) writeDirectAssembly() {
	if !cgoDirectSupported() {
		return
	}
	f := creat("_cgo_direct.s")
	defer f.Close()

	fmt.Fprintln(f, "// Code generated by cmd/cgo; DO NOT EDIT.")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "#include \"textflag.h\"")
	for _, call := range p.directCalls {
		fmt.Fprintln(f)
		p.writeDirectAssemblyCall(f, call)
	}
}

func (p *Package) writeDirectAssemblyCall(w io.Writer, call cgoDirectCall) {
	offsets, resultOffset, frameSize := cgoDirectFrame(call, p.PtrSize)
	fmt.Fprintf(w, "TEXT ·%s(SB),NOSPLIT,$0-%d\n", call.direct, frameSize)
	for i, param := range call.params {
		fmt.Fprintf(w, "\t%s\tp%d+%d(FP), %s\n",
			cgoDirectLoad(buildcfg.GOARCH, param), i, offsets[i],
			cgoDirectArgRegister(buildcfg.GOARCH, i))
	}
	for _, instruction := range cgoDirectCallInstructions(buildcfg.GOARCH, call.entry) {
		fmt.Fprintf(w, "\t%s\n", instruction)
	}
	if call.result != cgoDirectVoid {
		fmt.Fprintf(w, "\t%s\t%s, ret+%d(FP)\n",
			cgoDirectStore(buildcfg.GOARCH, call.result),
			cgoDirectResultRegister(buildcfg.GOARCH), resultOffset)
	}
	fmt.Fprintln(w, "\tRET")
}

func cgoDirectCallInstructions(goarch, entry string) []string {
	call := "CALL\t" + entry + "(SB)"
	switch goarch {
	case "arm64":
		// A Go frame saves its frame pointer just below SP. Keep the C
		// callee's frame below that slot.
		return []string{
			"SUB\t$16, RSP",
			call,
			"ADD\t$16, RSP",
		}
	case "amd64":
		return []string{
			"MOVQ\tSP, R12",
			"ANDQ\t$~15, SP",
			call,
			"MOVQ\tR12, SP",
		}
	default:
		return []string{call}
	}
}

// writeDirectCBridge gives every supported declaration an externally visible
// typed symbol in the C translation unit that contains its preamble. This
// keeps static and inline declarations usable without the general cgo
// argument-frame wrapper.
func (p *Package) writeDirectCBridge(w io.Writer, n *Name, call cgoDirectCall) {
	fmt.Fprintln(w, "CGO_NO_SANITIZE_THREAD")
	if result := n.FuncType.Result; result != nil {
		fmt.Fprintln(w, cgoDirectCType(result))
	} else {
		fmt.Fprintln(w, "void")
	}
	fmt.Fprintf(w, "%s(", call.entry)
	for i, param := range n.FuncType.Params {
		if i != 0 {
			fmt.Fprint(w, ", ")
		}
		fmt.Fprintf(w, "%s p%d", cgoDirectCType(param), i)
	}
	fmt.Fprintln(w, ")")
	fmt.Fprintln(w, "{")
	fmt.Fprint(w, "\t")
	if n.FuncType.Result != nil {
		fmt.Fprint(w, "return ")
	}
	fmt.Fprintf(w, "%s(", n.C)
	for i := range n.FuncType.Params {
		if i != 0 {
			fmt.Fprint(w, ", ")
		}
		fmt.Fprintf(w, "p%d", i)
	}
	fmt.Fprintln(w, ");")
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w)
}

func cgoDirectCType(typ *Type) string {
	if typ.Typedef != "" {
		return typ.Typedef
	}
	return typ.C.String()
}

func cgoDirectFrame(call cgoDirectCall, ptrSize int64) (params []int64, result, size int64) {
	params = make([]int64, len(call.params))
	var offset int64
	for i, param := range call.params {
		align := param.size()
		if align > ptrSize {
			align = ptrSize
		}
		offset = cgoDirectAlign(offset, align)
		params[i] = offset
		offset += param.size()
	}
	if call.result == cgoDirectVoid {
		return params, 0, offset
	}
	offset = cgoDirectAlign(offset, ptrSize)
	offset = cgoDirectAlign(offset, call.result.size())
	result = offset
	return params, result, result + call.result.size()
}

func cgoDirectAlign(value, align int64) int64 {
	return (value + align - 1) &^ (align - 1)
}

func (typ cgoDirectType) size() int64 {
	switch typ {
	case cgoDirectInt8, cgoDirectUint8:
		return 1
	case cgoDirectInt16, cgoDirectUint16:
		return 2
	case cgoDirectInt32, cgoDirectUint32:
		return 4
	case cgoDirectInt64, cgoDirectUint64, cgoDirectPointer:
		return 8
	}
	return 0
}

func cgoDirectLoad(goarch string, typ cgoDirectType) string {
	if goarch == "arm64" {
		switch typ {
		case cgoDirectInt8:
			return "MOVB"
		case cgoDirectUint8:
			return "MOVBU"
		case cgoDirectInt16:
			return "MOVH"
		case cgoDirectUint16:
			return "MOVHU"
		case cgoDirectInt32:
			return "MOVW"
		case cgoDirectUint32:
			return "MOVWU"
		default:
			return "MOVD"
		}
	}
	switch typ {
	case cgoDirectInt8:
		return "MOVBQSX"
	case cgoDirectUint8:
		return "MOVBQZX"
	case cgoDirectInt16:
		return "MOVWQSX"
	case cgoDirectUint16:
		return "MOVWQZX"
	case cgoDirectInt32:
		return "MOVLQSX"
	case cgoDirectUint32:
		return "MOVL"
	default:
		return "MOVQ"
	}
}

func cgoDirectStore(goarch string, typ cgoDirectType) string {
	if goarch == "arm64" {
		switch typ.size() {
		case 1:
			return "MOVB"
		case 2:
			return "MOVH"
		case 4:
			return "MOVW"
		default:
			return "MOVD"
		}
	}
	switch typ.size() {
	case 1:
		return "MOVB"
	case 2:
		return "MOVW"
	case 4:
		return "MOVL"
	default:
		return "MOVQ"
	}
}

func cgoDirectArgRegister(goarch string, index int) string {
	if goarch == "arm64" {
		return fmt.Sprintf("R%d", index)
	}
	return [...]string{"DI", "SI", "DX", "CX", "R8", "R9"}[index]
}

func cgoDirectResultRegister(goarch string) string {
	if goarch == "arm64" {
		return "R0"
	}
	return "AX"
}

func cgoDirectTypeOf(t *Type) (cgoDirectType, bool) {
	if t == nil {
		return cgoDirectVoid, true
	}
	if t.BadPointer {
		return cgoDirectPointer, true
	}
	return cgoDirectTypeOfExpr(t.Go, t.Size, make(map[string]bool))
}

func cgoDirectTypeOfExpr(expr ast.Expr, size int64, seen map[string]bool) (cgoDirectType, bool) {
	switch expr := expr.(type) {
	case *ast.StarExpr:
		return cgoDirectPointer, true
	case *ast.Ident:
		name := expr.Name
		if strings.HasPrefix(name, "_Ctype_") {
			if seen[name] {
				return "", false
			}
			underlying := typedef[name]
			if underlying == nil {
				return "", false
			}
			seen[name] = true
			return cgoDirectTypeOfExpr(underlying.Go, underlying.Size, seen)
		}
		switch name {
		case "unsafe.Pointer":
			return cgoDirectPointer, true
		case "bool", "byte", "uint8":
			return cgoDirectUint8, size == 1
		case "int8":
			return cgoDirectInt8, size == 1
		case "uint16":
			return cgoDirectUint16, size == 2
		case "int16":
			return cgoDirectInt16, size == 2
		case "uint32":
			return cgoDirectUint32, size == 4
		case "int32":
			return cgoDirectInt32, size == 4
		case "uint64":
			return cgoDirectUint64, size == 8
		case "int64":
			return cgoDirectInt64, size == 8
		case "uint", "uintptr":
			switch size {
			case 4:
				return cgoDirectUint32, true
			case 8:
				return cgoDirectUint64, true
			}
		case "int":
			switch size {
			case 4:
				return cgoDirectInt32, true
			case 8:
				return cgoDirectInt64, true
			}
		}
	}
	return "", false
}
