// Copyright 2026 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package main

import (
	"fmt"
	"go/ast"
	"io"
	"strconv"
	"strings"

	"internal/buildcfg"
)

const cgoDirectVersion = "v1"

const (
	cgoDirectMaxAggregateSize  = 128
	cgoDirectMaxAggregateAlign = 8
)

type cgoDirectType string

const (
	cgoDirectInt8    cgoDirectType = "i8"
	cgoDirectInt16   cgoDirectType = "i16"
	cgoDirectInt32   cgoDirectType = "i32"
	cgoDirectInt64   cgoDirectType = "i64"
	cgoDirectUint8   cgoDirectType = "u8"
	cgoDirectUint16  cgoDirectType = "u16"
	cgoDirectUint32  cgoDirectType = "u32"
	cgoDirectUint64  cgoDirectType = "u64"
	cgoDirectFloat32 cgoDirectType = "f32"
	cgoDirectFloat64 cgoDirectType = "f64"
	cgoDirectPointer cgoDirectType = "ptr"
	cgoDirectMemory  cgoDirectType = "mem"
	cgoDirectVoid    cgoDirectType = "void"
)

// cgoDirectValue describes one Go-visible value and how the generated C
// bridge receives it. Scalar values use their platform register class.
// Pointer-free aggregate values are passed to the bridge by address, leaving
// the C compiler responsible for the target function's aggregate ABI.
type cgoDirectValue struct {
	typ   cgoDirectType
	width int64
	align int64
}

type cgoDirectCall struct {
	wrapper string
	direct  string
	symbol  string
	entry   string
	params  []cgoDirectValue
	result  cgoDirectValue
	errno   bool
}

func (p *Package) directCall(n *Name) (cgoDirectCall, bool) {
	if !cgoDirectSupported() || *gccgo || n.Kind != "func" ||
		n.FuncType == nil || !p.noCallbacks[n.C] ||
		!validCgoDirectSymbol(n.C) {
		return cgoDirectCall{}, false
	}

	params := make([]cgoDirectValue, len(n.FuncType.Params))
	for i, param := range n.FuncType.Params {
		var ok bool
		params[i], ok = cgoDirectValueOf(param)
		if !ok || params[i].typ == cgoDirectVoid {
			return cgoDirectCall{}, false
		}
	}
	result := cgoDirectValue{typ: cgoDirectVoid}
	if n.FuncType.Result != nil {
		var ok bool
		result, ok = cgoDirectValueOf(n.FuncType.Result)
		if !ok || result.typ == cgoDirectVoid {
			return cgoDirectCall{}, false
		}
	}

	call := cgoDirectCall{
		wrapper: n.Mangle,
		symbol:  n.C,
		entry:   fmt.Sprintf("_cgo%s%s_direct", cPrefix, n.Mangle),
		params:  params,
		result:  result,
		errno:   n.AddError,
	}
	if _, ok := cgoDirectArgRegisters(buildcfg.GOARCH, call.bridgeParams()); !ok {
		return cgoDirectCall{}, false
	}

	var direct string
	switch {
	case !n.AddError && strings.HasPrefix(n.Mangle, "_Cfunc_"):
		direct = "_Cdirect_" + strings.TrimPrefix(n.Mangle, "_Cfunc_")
	case n.AddError && strings.HasPrefix(n.Mangle, "_C2func_"):
		direct = "_Cdirect2_" + strings.TrimPrefix(n.Mangle, "_C2func_")
	default:
		return cgoDirectCall{}, false
	}
	call.direct = direct
	return call, true
}

func cgoDirectSupported() bool {
	if !buildcfg.Experiment.Coro {
		return false
	}
	return buildcfg.GOOS == "darwin" && buildcfg.GOARCH == "arm64" ||
		buildcfg.GOOS == "linux" && buildcfg.GOARCH == "amd64"
}

func validCgoDirectSymbol(name string) bool {
	if name == "" || !isCgoDirectIdentStart(name[0]) {
		return false
	}
	for i := 1; i < len(name); i++ {
		if !isCgoDirectIdentStart(name[i]) && (name[i] < '0' || name[i] > '9') {
			return false
		}
	}
	return true
}

func isCgoDirectIdentStart(ch byte) bool {
	return ch == '_' || ch >= 'a' && ch <= 'z' || ch >= 'A' && ch <= 'Z'
}

func (call cgoDirectCall) writeDirective(w io.Writer) {
	params := "-"
	if len(call.params) != 0 {
		names := make([]string, len(call.params))
		for i, param := range call.params {
			names[i] = param.String()
		}
		params = strings.Join(names, ",")
	}
	errno := "-"
	if call.errno {
		errno = "errno"
	}
	fmt.Fprintf(w, "//go:cgo_direct %s %s %s %s mayblock %s %s %s\n",
		cgoDirectVersion, call.wrapper, call.direct, call.symbol,
		params, call.result, errno)
}

func (p *Package) writeDirectAssembly() {
	if !cgoDirectSupported() {
		return
	}
	f := creat("_cgo_direct.s")
	defer f.Close()

	fmt.Fprintln(f, "// Code generated by cmd/cgo; DO NOT EDIT.")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "#include \"textflag.h\"")
	for _, call := range p.directCalls {
		fmt.Fprintln(f)
		p.writeDirectAssemblyCall(f, call)
	}
}

func (p *Package) writeDirectAssemblyCall(w io.Writer, call cgoDirectCall) {
	offsets, resultOffset, errnoOffset, frameSize := cgoDirectFrame(call, p.PtrSize)
	registers, _ := cgoDirectArgRegisters(buildcfg.GOARCH, call.bridgeParams())
	fmt.Fprintf(w, "TEXT ·%s(SB),NOSPLIT,$0-%d\n", call.direct, frameSize)
	for i, param := range call.params {
		if param.typ == cgoDirectMemory {
			writeDirectAddress(w, fmt.Sprintf("p%d+%d(FP)", i, offsets[i]),
				registers[i])
		} else {
			fmt.Fprintf(w, "\t%s\tp%d+%d(FP), %s\n",
				cgoDirectLoad(buildcfg.GOARCH, param.typ), i, offsets[i],
				registers[i])
		}
	}
	if call.indirectResult() {
		writeDirectAddress(w, fmt.Sprintf("ret+%d(FP)", resultOffset),
			registers[len(call.params)])
	}
	for _, instruction := range cgoDirectCallInstructions(buildcfg.GOARCH, call.entry) {
		fmt.Fprintf(w, "\t%s\n", instruction)
	}
	if call.errno {
		fmt.Fprintf(w, "\t%s\t%s, errno+%d(FP)\n",
			cgoDirectStore(buildcfg.GOARCH, cgoDirectPointer),
			cgoDirectResultRegister(buildcfg.GOARCH, cgoDirectPointer),
			errnoOffset)
	} else if call.result.typ != cgoDirectVoid &&
		call.result.typ != cgoDirectMemory {
		fmt.Fprintf(w, "\t%s\t%s, ret+%d(FP)\n",
			cgoDirectStore(buildcfg.GOARCH, call.result.typ),
			cgoDirectResultRegister(buildcfg.GOARCH, call.result.typ), resultOffset)
	}
	fmt.Fprintln(w, "\tRET")
}

func writeDirectAddress(w io.Writer, address, register string) {
	if buildcfg.GOARCH == "arm64" {
		address = "$" + address
	}
	fmt.Fprintf(w, "\t%s\t%s, %s\n",
		cgoDirectAddress(buildcfg.GOARCH), address, register)
}

func cgoDirectCallInstructions(goarch, entry string) []string {
	call := "CALL\t" + entry + "(SB)"
	switch goarch {
	case "arm64":
		// A Go frame saves its frame pointer just below SP. Keep the C
		// callee's frame below that slot.
		return []string{
			"SUB\t$16, RSP",
			call,
			"ADD\t$16, RSP",
		}
	case "amd64":
		return []string{
			"MOVQ\tSP, R12",
			"ANDQ\t$~15, SP",
			call,
			"MOVQ\tR12, SP",
		}
	default:
		return []string{call}
	}
}

// writeDirectCBridge gives every supported declaration an externally visible
// typed symbol in the C translation unit that contains its preamble. This
// keeps static and inline declarations usable without the general cgo
// argument-frame wrapper.
func (p *Package) writeDirectCBridge(w io.Writer, n *Name, call cgoDirectCall) {
	fmt.Fprintln(w, "CGO_NO_SANITIZE_THREAD")
	if call.errno {
		fmt.Fprintln(w, "size_t")
	} else if call.result.typ == cgoDirectMemory {
		fmt.Fprintln(w, "void")
	} else if result := n.FuncType.Result; result != nil {
		fmt.Fprintln(w, cgoDirectCType(result))
	} else {
		fmt.Fprintln(w, "void")
	}
	fmt.Fprintf(w, "%s(", call.entry)
	for i, param := range n.FuncType.Params {
		if i != 0 {
			fmt.Fprint(w, ", ")
		}
		if call.params[i].typ == cgoDirectMemory {
			fmt.Fprintf(w, "const %s *p%d", cgoDirectCType(param), i)
		} else {
			fmt.Fprintf(w, "%s p%d", cgoDirectCType(param), i)
		}
	}
	if call.indirectResult() {
		if len(n.FuncType.Params) != 0 {
			fmt.Fprint(w, ", ")
		}
		fmt.Fprintf(w, "%s *result", cgoDirectCType(n.FuncType.Result))
	}
	fmt.Fprintln(w, ")")
	fmt.Fprintln(w, "{")
	if call.errno {
		if n.FuncType.Result != nil {
			fmt.Fprintf(w, "\t%s value;\n", cgoDirectCType(n.FuncType.Result))
		}
		fmt.Fprintln(w, "\tint saved_errno;")
		fmt.Fprintln(w, "\terrno = 0;")
	}
	fmt.Fprint(w, "\t")
	if call.errno && n.FuncType.Result != nil {
		fmt.Fprint(w, "value = ")
	} else if call.result.typ == cgoDirectMemory {
		fmt.Fprint(w, "*result = ")
	} else if !call.errno && n.FuncType.Result != nil {
		fmt.Fprint(w, "return ")
	}
	fmt.Fprintf(w, "%s(", n.C)
	for i := range n.FuncType.Params {
		if i != 0 {
			fmt.Fprint(w, ", ")
		}
		if call.params[i].typ == cgoDirectMemory {
			fmt.Fprintf(w, "*p%d", i)
		} else {
			fmt.Fprintf(w, "p%d", i)
		}
	}
	fmt.Fprintln(w, ");")
	if call.errno {
		fmt.Fprintln(w, "\tsaved_errno = errno;")
		if n.FuncType.Result != nil {
			fmt.Fprintln(w, "\t*result = value;")
		}
		fmt.Fprintln(w, "\treturn (size_t)saved_errno;")
	}
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w)
}

func cgoDirectCType(typ *Type) string {
	if typ.Typedef != "" {
		return typ.Typedef
	}
	return typ.C.String()
}

func cgoDirectFrame(call cgoDirectCall, ptrSize int64) (params []int64, result, errno, size int64) {
	params = make([]int64, len(call.params))
	var offset int64
	for i, param := range call.params {
		align := param.alignment(ptrSize)
		offset = cgoDirectAlign(offset, align)
		params[i] = offset
		offset += param.size()
	}
	if call.result.typ != cgoDirectVoid {
		offset = cgoDirectAlign(offset, ptrSize)
		offset = cgoDirectAlign(offset, call.result.alignment(ptrSize))
		result = offset
		offset += call.result.size()
	}
	if call.errno {
		offset = cgoDirectAlign(offset, ptrSize)
		errno = offset
		offset += ptrSize
	}
	return params, result, errno, offset
}

func cgoDirectAlign(value, align int64) int64 {
	return (value + align - 1) &^ (align - 1)
}

func (call cgoDirectCall) bridgeParams() []cgoDirectType {
	params := make([]cgoDirectType, 0, len(call.params)+1)
	for _, param := range call.params {
		params = append(params, param.bridgeType())
	}
	if call.indirectResult() {
		params = append(params, cgoDirectPointer)
	}
	return params
}

func (call cgoDirectCall) indirectResult() bool {
	return call.result.typ == cgoDirectMemory ||
		call.errno && call.result.typ != cgoDirectVoid
}

func (value cgoDirectValue) String() string {
	if value.typ != cgoDirectMemory {
		return string(value.typ)
	}
	return "mem" + strconv.FormatInt(value.width, 10) + ":" +
		strconv.FormatInt(value.align, 10)
}

func (value cgoDirectValue) bridgeType() cgoDirectType {
	if value.typ == cgoDirectMemory {
		return cgoDirectPointer
	}
	return value.typ
}

func (value cgoDirectValue) size() int64 {
	if value.typ == cgoDirectMemory {
		return value.width
	}
	return value.typ.size()
}

func (value cgoDirectValue) alignment(ptrSize int64) int64 {
	align := value.align
	if align == 0 {
		align = value.size()
	}
	if align > ptrSize {
		align = ptrSize
	}
	return align
}

func (typ cgoDirectType) size() int64 {
	switch typ {
	case cgoDirectInt8, cgoDirectUint8:
		return 1
	case cgoDirectInt16, cgoDirectUint16:
		return 2
	case cgoDirectInt32, cgoDirectUint32, cgoDirectFloat32:
		return 4
	case cgoDirectInt64, cgoDirectUint64, cgoDirectFloat64, cgoDirectPointer:
		return 8
	}
	return 0
}

func cgoDirectLoad(goarch string, typ cgoDirectType) string {
	if goarch == "arm64" {
		switch typ {
		case cgoDirectFloat32:
			return "FMOVS"
		case cgoDirectFloat64:
			return "FMOVD"
		case cgoDirectInt8:
			return "MOVB"
		case cgoDirectUint8:
			return "MOVBU"
		case cgoDirectInt16:
			return "MOVH"
		case cgoDirectUint16:
			return "MOVHU"
		case cgoDirectInt32:
			return "MOVW"
		case cgoDirectUint32:
			return "MOVWU"
		default:
			return "MOVD"
		}
	}
	switch typ {
	case cgoDirectFloat32:
		return "MOVSS"
	case cgoDirectFloat64:
		return "MOVSD"
	case cgoDirectInt8:
		return "MOVBQSX"
	case cgoDirectUint8:
		return "MOVBQZX"
	case cgoDirectInt16:
		return "MOVWQSX"
	case cgoDirectUint16:
		return "MOVWQZX"
	case cgoDirectInt32:
		return "MOVLQSX"
	case cgoDirectUint32:
		return "MOVL"
	default:
		return "MOVQ"
	}
}

func cgoDirectStore(goarch string, typ cgoDirectType) string {
	if goarch == "arm64" {
		switch typ {
		case cgoDirectFloat32:
			return "FMOVS"
		case cgoDirectFloat64:
			return "FMOVD"
		}
		switch typ.size() {
		case 1:
			return "MOVB"
		case 2:
			return "MOVH"
		case 4:
			return "MOVW"
		default:
			return "MOVD"
		}
	}
	switch typ {
	case cgoDirectFloat32:
		return "MOVSS"
	case cgoDirectFloat64:
		return "MOVSD"
	}
	switch typ.size() {
	case 1:
		return "MOVB"
	case 2:
		return "MOVW"
	case 4:
		return "MOVL"
	default:
		return "MOVQ"
	}
}

func cgoDirectAddress(goarch string) string {
	if goarch == "arm64" {
		return "MOVD"
	}
	return "LEAQ"
}

// cgoDirectArgRegisters assigns the independent integer and floating-point
// register classes of the target System ABI.
func cgoDirectArgRegisters(goarch string, params []cgoDirectType) ([]string, bool) {
	registers := make([]string, len(params))
	var integer, floating int
	for i, param := range params {
		if param.isFloat() {
			if floating >= 8 {
				return nil, false
			}
			if goarch == "arm64" {
				registers[i] = fmt.Sprintf("F%d", floating)
			} else if goarch == "amd64" {
				registers[i] = fmt.Sprintf("X%d", floating)
			} else {
				return nil, false
			}
			floating++
			continue
		}
		if goarch == "arm64" {
			if integer >= 8 {
				return nil, false
			}
			registers[i] = fmt.Sprintf("R%d", integer)
		} else if goarch == "amd64" {
			if integer >= 6 {
				return nil, false
			}
			registers[i] = [...]string{"DI", "SI", "DX", "CX", "R8", "R9"}[integer]
		} else {
			return nil, false
		}
		integer++
	}
	return registers, true
}

func cgoDirectResultRegister(goarch string, typ cgoDirectType) string {
	if typ.isFloat() {
		if goarch == "arm64" {
			return "F0"
		}
		return "X0"
	}
	if goarch == "arm64" {
		return "R0"
	}
	return "AX"
}

func (typ cgoDirectType) isFloat() bool {
	return typ == cgoDirectFloat32 || typ == cgoDirectFloat64
}

func cgoDirectValueOf(t *Type) (cgoDirectValue, bool) {
	typ, ok := cgoDirectTypeOf(t)
	if ok {
		return cgoDirectValue{typ: typ}, true
	}
	if t == nil || t.Size <= 0 || t.Size > cgoDirectMaxAggregateSize ||
		t.Align <= 0 || t.Align > cgoDirectMaxAggregateAlign ||
		t.Align&(t.Align-1) != 0 ||
		!cgoDirectAggregate(t.Go, make(map[string]bool)) {
		return cgoDirectValue{}, false
	}
	return cgoDirectValue{
		typ:   cgoDirectMemory,
		width: t.Size,
		align: t.Align,
	}, true
}

func cgoDirectAggregate(expr ast.Expr, seen map[string]bool) bool {
	switch expr := expr.(type) {
	case *ast.StructType:
		for _, field := range expr.Fields.List {
			if !cgoDirectMemorySafe(field.Type, seen) {
				return false
			}
		}
		return true
	case *ast.Ident:
		if strings.HasPrefix(expr.Name, "_Ctype_union_") ||
			strings.HasPrefix(expr.Name, "_Ctype_class_") ||
			seen[expr.Name] {
			return false
		}
		underlying := typedef[expr.Name]
		if underlying == nil {
			return false
		}
		seen[expr.Name] = true
		ok := cgoDirectAggregate(underlying.Go, seen)
		delete(seen, expr.Name)
		return ok
	}
	return false
}

func cgoDirectMemorySafe(expr ast.Expr, seen map[string]bool) bool {
	switch expr := expr.(type) {
	case *ast.ArrayType:
		return expr.Len != nil && cgoDirectMemorySafe(expr.Elt, seen)
	case *ast.StructType:
		for _, field := range expr.Fields.List {
			if !cgoDirectMemorySafe(field.Type, seen) {
				return false
			}
		}
		return true
	case *ast.Ident:
		switch expr.Name {
		case "bool", "byte", "uint8", "int8", "uint16", "int16",
			"uint32", "int32", "uint64", "int64", "uint", "int",
			"uintptr", "float32", "float64", "complex64", "complex128":
			return true
		}
		if strings.HasPrefix(expr.Name, "_Ctype_union_") ||
			strings.HasPrefix(expr.Name, "_Ctype_class_") ||
			seen[expr.Name] {
			return false
		}
		underlying := typedef[expr.Name]
		if underlying == nil || underlying.BadPointer {
			return false
		}
		seen[expr.Name] = true
		ok := cgoDirectMemorySafe(underlying.Go, seen)
		delete(seen, expr.Name)
		return ok
	}
	return false
}

func cgoDirectTypeOf(t *Type) (cgoDirectType, bool) {
	if t == nil {
		return cgoDirectVoid, true
	}
	if t.BadPointer {
		return cgoDirectPointer, true
	}
	return cgoDirectTypeOfExpr(t.Go, t.Size, make(map[string]bool))
}

func cgoDirectTypeOfExpr(expr ast.Expr, size int64, seen map[string]bool) (cgoDirectType, bool) {
	switch expr := expr.(type) {
	case *ast.StarExpr:
		return cgoDirectPointer, true
	case *ast.Ident:
		name := expr.Name
		if strings.HasPrefix(name, "_Ctype_") {
			if seen[name] {
				return "", false
			}
			underlying := typedef[name]
			if underlying == nil {
				return "", false
			}
			seen[name] = true
			return cgoDirectTypeOfExpr(underlying.Go, underlying.Size, seen)
		}
		switch name {
		case "unsafe.Pointer":
			return cgoDirectPointer, true
		case "bool", "byte", "uint8":
			return cgoDirectUint8, size == 1
		case "int8":
			return cgoDirectInt8, size == 1
		case "uint16":
			return cgoDirectUint16, size == 2
		case "int16":
			return cgoDirectInt16, size == 2
		case "uint32":
			return cgoDirectUint32, size == 4
		case "int32":
			return cgoDirectInt32, size == 4
		case "uint64":
			return cgoDirectUint64, size == 8
		case "int64":
			return cgoDirectInt64, size == 8
		case "float32":
			return cgoDirectFloat32, size == 4
		case "float64":
			return cgoDirectFloat64, size == 8
		case "uint", "uintptr":
			switch size {
			case 4:
				return cgoDirectUint32, true
			case 8:
				return cgoDirectUint64, true
			}
		case "int":
			switch size {
			case 4:
				return cgoDirectInt32, true
			case 8:
				return cgoDirectInt64, true
			}
		}
	}
	return "", false
}
